; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes='lower-sparse-intrinsics' -S < %s | FileCheck %s

define void @store_tiny(<6 x float> %in, ptr %out) {
; CHECK-LABEL: @store_tiny(
; CHECK-NEXT:    store <6 x float> [[IN:%.*]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  call void @llvm.csc.matrix.store(<6 x float> %in, ptr %out)
  ret void
}

declare void @llvm.csc.matrix.store(<6 x float>, ptr)
